### ISSUE TITLE
关于项目如何使用的提问

### ISSUE THREAD

**Issue by charmtiger** [xiaoyanLG/Soft-keyboard#1]
作者您好！
请问 soft-keyboard 是如何使用的? 我想知道如果使用 webview 来加载远程的html，input 输入框获得焦点后，能否吊起 soft-keyboard。系统是 linux armbian 或 Ubuntu 。

**Comment by xiaoyanLG** [comment]
这个没试过，不好意思，你可以试试，我觉得找对方法应该可以！
