### ISSUE TITLE
英文输入不了的问题

### ISSUE THREAD

**Issue by xiedonghuilove** [xiaoyanLG/Soft-keyboard#2]
非常感谢您的开源，我下载了你的源码。发现在demo中，英文输入不了，中文可以输入。我看了代码，好像是：
QWSServer::sendKeyEvent(unicode, keycode, (Qt::KeyboardModifiers)modifiers, isPress, false);
这句话引起的，在源码中，你注释掉了。
我现在的环境是Qt5  我发现只有Qt4 才有QWS这个类。请问，我在Qt5中该如何使用呢？

**Comment by xiaoyanLG** [comment]
已提交修改，请更新最新源码！
